name: Build Test
run-name: Build Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "Switch working directory"
      - run: cd ./mui-atomic

      - name: Install dependencies
        run: npm install --foreground-scripts

      - name: Run build
        run: npm run build
